name: Rivky First Action
run-name: ${{github.actor}} is testing out github actions
on: push
jobs:
  Explore-Interesting-Stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automagically triggered by a ${{github.event_name}}"
      - run: echo "Runner OS is ${{runner.os}}. Name of branch is ${{github.ref}}. Repository is ${{github.repository}}"
      - name: Check out Repository
        uses: actions/checkout@v3
      - run: echo "The ${{github.repository}} repo has been cloned to the runner."
      - name: List All Files
        run: ls
      - name: List project Files
        run: ls ${{github.workspace}}
      - run: echo "The jobs status is ${{job.status}}"